name: "SpigotGuard"
version: "5.7 BULLET-PROOF"
main: "xyz.yooniks.spigotguard.SpigotGuardPlugin"
authors: ["yooniks"]
author: "yooniks"
description: "Advanced protection against crashers and exploits for minecraft servers: https://minemen.com/resources/175/"
website: "https://minemen.com/resources/175/"
softdepend:
  - ViaVersion
commands:
  spigotguard:
    aliases:
      - anticrash
      - antycrash
      - guardspigot
      - exploitfixer
      - spigotg
      - ef
      - protection
      - unioanticrash
      - safemc
      - xprotector
      - unioanticrash
    description: "The main command of SpigotGuard plugin"
api-version: 1.13