name: "SpigotGuard"
version: "6.4.2 BULLET-PROOF"
main: "xyz.yooniks.spigotguard.SpigotGuardPlugin"
authors: ["yooniks"]
author: "yooniks"
description: "Advanced protection against crashers and exploits for minecraft servers: https://mc-protection.eu"
website: "https://mc-protection.eu"
loadbefore:
  - ViaVersion
softdepend:
  - ViaVersion
  - FastAsyncWorldEdit
commands:
  spigotguard:
    aliases:
      - anticrash
      - antycrash
      - guardspigot
      - exploitfixer
      - spigotg
      - ef
      - protection
      - unioanticrash
      - safemc
      - xprotector
      - unioanticrash
    description: "The main command of SpigotGuard plugin"
api-version: 1.13